
const quizQuestion = [
    {
        questionNo: 1,
        question: "Which river is known as the 'Ganga of the South' in India?",
        options: ["Yamuna", "Godavari", "Krishna", "Cauvery"],
        //answer: "Krishna",
        //points: 5,
    },
    {
        questionNo: 2,
        question: "Who is known as the 'Iron Man of India'?",
        options: ["Sardar Patel", "Subhas Chandra Bose", "Mahatma Gandhi", "Jawaharlal Nehru"],
        //answer: "Sardar Patel",
        //points: 5,
    },
    {
        questionNo: 3,
        question: "In which year did India gain independence?",
        options: ["1942", "1947", "1950", "1962"],
        //answer: "1947",
        //points: 5,
    },
    {
        questionNo: 4,
        question: "Which Indian state is known as the 'Land of Five Rivers'?",
        options: ["Punjab", "Haryana", "Rajasthan", "Gujarat"],
        //answer: "Punjab",
        //points: 5,
    },
    {
        questionNo: 5,
        question: "Who was the first woman Prime Minister of India?",
        options: ["Indira Gandhi", "Sonia Gandhi", "Pratibha Patil", "Sheila Dikshit"],
        //answer: "Indira Gandhi",
        //points: 5,
    },
    {
        questionNo: 6,
        question: "What is the national currency of India?",
        options: ["Rupee", "Rupiah", "Ringgit", "Yen"],
        //answer: "Rupee",
        //points: 5,
    },
    {
        questionNo: 7,
        question: "Which Indian mathematician introduced the concept of zero?",
        options: ["Aryabhata", "Bhaskara I", "Brahmagupta", "Srinivasa Ramanujan"],
        //answer: "Brahmagupta",
        //points: 5,
    },
    {
        questionNo: 8,
        question: "Which Indian festival is known as the 'Festival of Lights'?",
        options: ["Holi", "Diwali", "Navratri", "Eid"],
        //answer: "Diwali",
        //points: 5,
    },
    {
        questionNo: 9,
        question: "Who is known as the 'Missile Man of India'?",
        options: ["Dr. A. P. J. Abdul Kalam", "Atal Bihari Vajpayee", "Manmohan Singh", "Narendra Modi"],
        //answer: "Dr. A. P. J. Abdul Kalam",
        //points: 5,
    },
    {
        questionNo: 10,
        question: "Which Indian city is famous for its IT industry and is known as the 'Silicon Valley of India'?",
        options: ["Mumbai", "Bangalore", "Chennai", "Hyderabad"],
        //answer: "Bangalore",
        //points: 5,
    },
    {
        questionNo: 11,
        question: "In which year did India host its first Commonwealth Games?",
        options: ["1998", "2002", "2010", "2014"],
        //   answer: "2010",
        //   points: 5,
    },
    {
        questionNo: 12,
        question: "Who is the 'God of Cricket' in India?",
        options: ["Sachin Tendulkar", "Virat Kohli", "Rahul Dravid", "Virender Sehwag"],
        //   answer: "Sachin Tendulkar",
        //   points: 5,
    },
    {
        questionNo: 13,
        question: "Which Indian city is known as the 'City of Joy'?",
        options: ["Kolkata", "Mumbai", "Delhi", "Chennai"],
        //   answer: "Kolkata",
        //   points: 5,
    },
    {
        questionNo: 14,
        question: "What is the official language of the Indian state of Maharashtra?",
        options: ["Hindi", "Marathi", "Telugu", "Bengali"],
        //   answer: "Marathi",
        //   points: 5,
    },
    {
        questionNo: 15,
        question: "Who was the first woman to win an individual Olympic silver medal for India?",
        options: ["P. T. Usha", "Saina Nehwal", "Mary Kom", "PV Sindhu"],
        //   answer: "PV Sindhu",
        //   points: 5,
    },
]

module.exports = { quizQuestion }